import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";

import "./globals.css";
import clsx from "clsx";
import Header from "@/componenta/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, styles.body)}>
        <Header />
        {children}</body>
    </html>
  );
}
